import fs from "node:fs/promises";
import path from "node:path";
import { createSupabaseAdminClient } from "@/lib/supabase/admin";

export interface FileContentResolver {
  /**
   * Read raw bytes for a stored file. Used for bytes-first prompt hydration.
   */
  readBytes(ref: string): Promise<Uint8Array>;
  /**
   * Resolve a reference key to a public URL. Intended for UI replay/rendering.
   * This URL MUST NOT be assumed to be accessible by model providers.
   *
   * NOTE: This method is currently not used by the bytes-first model hydration path.
   * It is kept intentionally for future cloud storage integration (public/signed URLs).
   */
  resolvePublicUrl(ref: string): Promise<string>;
}

export class LocalFileContentResolver implements FileContentResolver {
  private uploadDir: string;
  private publicPath: string;

  constructor(
    uploadDir = path.join(process.cwd(), "public", "uploads"),
    publicPath = "/uploads"
  ) {
    this.uploadDir = uploadDir;
    this.publicPath = publicPath;
  }

  async readBytes(ref: string): Promise<Uint8Array> {
    const filePath = path.join(this.uploadDir, ref);
    const buffer = await fs.readFile(filePath);
    return new Uint8Array(buffer);
  }

  async resolvePublicUrl(ref: string): Promise<string> {
    return `${this.publicPath}/${ref}`;
  }
}

export class SupabaseFileContentResolver implements FileContentResolver {
  private bucket: string;

  constructor(bucket: string) {
    this.bucket = bucket;
  }

  async readBytes(ref: string): Promise<Uint8Array> {
    const supabase = createSupabaseAdminClient();
    const { data, error } = await supabase.storage.from(this.bucket).download(ref);
    if (error || !data) {
      throw new Error(`Supabase download failed: ${error?.message ?? "unknown"}`);
    }
    const ab = await data.arrayBuffer();
    return new Uint8Array(ab);
  }

  async resolvePublicUrl(ref: string): Promise<string> {
    // For UI replay/rendering we prefer short-lived signed URLs.
    // This implementation returns a signed URL generated by Supabase.
    const ttl = Number(process.env.SUPABASE_SIGNED_URL_TTL_SECONDS ?? "300");
    const signedUrlTtlSeconds = Number.isFinite(ttl) && ttl > 0 ? ttl : 300;
    const supabase = createSupabaseAdminClient();
    const { data, error } = await supabase.storage
      .from(this.bucket)
      .createSignedUrl(ref, signedUrlTtlSeconds);
    if (error || !data?.signedUrl) {
      throw new Error(`Create signed URL failed: ${error?.message ?? "unknown"}`);
    }
    return data.signedUrl;
  }
}

function createFileContentResolver(): FileContentResolver {
  const driver =
    process.env.FILE_STORAGE_DRIVER ??
    (process.env.SUPABASE_SERVICE_ROLE_KEY ? "supabase" : "local");
  if (driver === "supabase") {
    const bucket = process.env.SUPABASE_STORAGE_BUCKET ?? "uploads";
    return new SupabaseFileContentResolver(bucket);
  }
  return new LocalFileContentResolver();
}

export const fileContentResolver: FileContentResolver = createFileContentResolver();

